import { ReviewDetail } from "./review-types";

export const reviewFixtures: ReviewDetail[] = [
  {
    id: "review-law-146",
    domain: "legal_document",
    title: "Cập nhật mức hưởng KCB trái tuyến",
    sourceName: "nghi-dinh-146-2018.md",
    submittedAt: "12 phút trước",
    status: "pending",
    confidence: 0.94,
    changedFileCount: 2,
    flags: ["Điều 14 thay đổi", "2 chunks mới"],
    summary: "Bổ sung diễn giải mức hưởng nội trú theo tuyến tỉnh và trung ương.",
    branchLabel: "ingest/legal-146-v3",
    submittedBy: "Hệ thống đồng bộ văn bản",
    files: [
      {
        path: "sources/legal/nghi-dinh-146-2018.md",
        beforeLabel: "v2 · 06/08/2026",
        afterLabel: "v3 · đề xuất",
        additions: 3,
        deletions: 1,
        lines: [
          { lineNumber: 118, kind: "context", text: "Điều 14. Mức hưởng khi khám chữa bệnh không đúng tuyến" },
          { lineNumber: 119, kind: "deletion", text: "Người bệnh được hưởng theo tỷ lệ quy định tại khoản 3." , evidenceIds: ["chunk-law-1"]},
          { lineNumber: 119, kind: "addition", text: "Người bệnh nội trú tại tuyến tỉnh được quỹ BHYT thanh toán theo mức hưởng." , evidenceIds: ["chunk-law-1"]},
          { lineNumber: 120, kind: "addition", text: "Tại tuyến trung ương, mức hưởng là 40% chi phí điều trị nội trú." , evidenceIds: ["chunk-law-2"]},
          { lineNumber: 121, kind: "addition", text: "Quy định này không áp dụng cho chi phí ngoại trú trái tuyến." , evidenceIds: ["chunk-law-2"]},
        ],
      },
      {
        path: "graph/entities.json",
        beforeLabel: "12 entities",
        afterLabel: "14 entities",
        additions: 2,
        deletions: 0,
        lines: [
          { lineNumber: 41, kind: "context", text: '"Nghị định 146/2018/NĐ-CP": { "type": "regulation" }' },
          { lineNumber: 42, kind: "addition", text: '"tuyến tỉnh": { "type": "care_route", "confidence": 0.98 }', evidenceIds: ["entity-route"] },
          { lineNumber: 43, kind: "addition", text: '"tuyến trung ương": { "type": "care_route", "confidence": 0.97 }', evidenceIds: ["entity-central"] },
        ],
      },
    ],
    chunks: [
      { id: "chunk-law-1", text: "Người bệnh nội trú tại tuyến tỉnh được quỹ BHYT thanh toán theo mức hưởng.", sourceFile: "nghi-dinh-146-2018.md", page: 8, lineRange: "118–119", confidence: 0.96 },
      { id: "chunk-law-2", text: "Tại tuyến trung ương, mức hưởng là 40% chi phí điều trị nội trú.", sourceFile: "nghi-dinh-146-2018.md", page: 8, lineRange: "120–121", confidence: 0.92 },
    ],
    entities: [
      { id: "entity-law", label: "Nghị định 146/2018/NĐ-CP", type: "Văn bản pháp quy", confidence: 0.99, chunkIds: ["chunk-law-1", "chunk-law-2"] },
      { id: "entity-route", label: "Tuyến tỉnh", type: "Tuyến KCB", confidence: 0.98, chunkIds: ["chunk-law-1"] },
      { id: "entity-central", label: "Tuyến trung ương", type: "Tuyến KCB", confidence: 0.97, chunkIds: ["chunk-law-2"] },
    ],
    relations: [
      { id: "relation-law-1", sourceEntityId: "entity-law", targetEntityId: "entity-route", label: "quy định mức hưởng", confidence: 0.95, evidenceChunkIds: ["chunk-law-1"] },
      { id: "relation-law-2", sourceEntityId: "entity-law", targetEntityId: "entity-central", label: "áp dụng cho", confidence: 0.94, evidenceChunkIds: ["chunk-law-2"] },
    ],
    ocrFields: [],
    audit: [{ id: "audit-law-1", action: "submitted", actor: "Ingest bot", at: "12 phút trước", note: "Phát hiện phiên bản mới từ nguồn pháp luật." }],
  },
  {
    id: "review-fee-072",
    domain: "hospital_fee_ocr",
    title: "Bảng kê viện phí · lượt khám 072",
    sourceName: "bang-ke-vien-phi-072.png",
    submittedAt: "39 phút trước",
    status: "pending",
    confidence: 0.81,
    changedFileCount: 1,
    flags: ["1 trường OCR thấp", "Cần kiểm tra số tiền"],
    summary: "OCR bảng kê đã chuẩn hóa 6 dòng chi phí và phát hiện một đơn giá cần xác nhận.",
    branchLabel: "ingest/ocr-fee-072",
    submittedBy: "OCR worker · batch 24",
    files: [
      {
        path: "sources/hospital-fees/bang-ke-vien-phi-072.json",
        beforeLabel: "ảnh gốc",
        afterLabel: "bản trích xuất · đề xuất",
        additions: 6,
        deletions: 2,
        lines: [
          { lineNumber: 7, kind: "context", text: '"facility": "Bệnh viện mẫu",' },
          { lineNumber: 8, kind: "deletion", text: '"service_name": "Xét nghiêm huyết học",' },
          { lineNumber: 8, kind: "addition", text: '"service_name": "Xét nghiệm huyết học",', evidenceIds: ["ocr-service"] },
          { lineNumber: 9, kind: "addition", text: '"quantity": 1,', evidenceIds: ["ocr-service"] },
          { lineNumber: 10, kind: "addition", text: '"unit_price": 185000,', evidenceIds: ["ocr-price"] },
          { lineNumber: 11, kind: "addition", text: '"insurance_covered": 148000,', evidenceIds: ["ocr-covered"] },
          { lineNumber: 12, kind: "addition", text: '"patient_amount": 37000', evidenceIds: ["ocr-patient"] },
          { lineNumber: 13, kind: "deletion", text: '"note": "đọc mờ"' },
        ],
      },
    ],
    chunks: [
      { id: "chunk-fee-1", text: "Xét nghiệm huyết học · SL 1 · Đơn giá 185.000đ · Quỹ BHYT 148.000đ · Người bệnh 37.000đ.", sourceFile: "bang-ke-vien-phi-072.json", page: 1, lineRange: "8–12", confidence: 0.81 },
      { id: "chunk-fee-2", text: "Tổng phần người bệnh của dòng chi phí: 37.000đ.", sourceFile: "bang-ke-vien-phi-072.json", page: 1, lineRange: "12", confidence: 0.88 },
    ],
    entities: [
      { id: "entity-service", label: "Xét nghiệm huyết học", type: "Dịch vụ y tế", confidence: 0.79, chunkIds: ["chunk-fee-1"] },
      { id: "entity-insurance", label: "Quỹ BHYT", type: "Bên chi trả", confidence: 0.91, chunkIds: ["chunk-fee-1"] },
      { id: "entity-patient", label: "Người bệnh", type: "Bên thanh toán", confidence: 0.93, chunkIds: ["chunk-fee-1", "chunk-fee-2"] },
    ],
    relations: [
      { id: "relation-fee-1", sourceEntityId: "entity-insurance", targetEntityId: "entity-service", label: "chi trả một phần", confidence: 0.9, evidenceChunkIds: ["chunk-fee-1"] },
      { id: "relation-fee-2", sourceEntityId: "entity-patient", targetEntityId: "entity-service", label: "thanh toán phần còn lại", confidence: 0.87, evidenceChunkIds: ["chunk-fee-1", "chunk-fee-2"] },
    ],
    ocrFields: [
      { id: "ocr-service", key: "service_name", value: "Xét nghiệm huyết học", rawValue: "Xét nghiêm huyết học", confidence: 0.79, sourcePage: 1, needsReview: true },
      { id: "ocr-price", key: "unit_price", value: "185.000đ", rawValue: "185000", confidence: 0.83, sourcePage: 1, needsReview: false },
      { id: "ocr-covered", key: "insurance_covered", value: "148.000đ", rawValue: "148000", confidence: 0.86, sourcePage: 1, needsReview: false },
      { id: "ocr-patient", key: "patient_amount", value: "37.000đ", rawValue: "37000", confidence: 0.89, sourcePage: 1, needsReview: false },
    ],
    audit: [{ id: "audit-fee-1", action: "submitted", actor: "OCR worker", at: "39 phút trước", note: "Tạo review từ ảnh bảng kê đã khử định danh." }],
  },
];
